[theme.dev]
refresh = -1
log = true
debug = false

[theme.options]
stealth_mode = false
boot_animation = true
boot_max_loops = 1
boot_total_duration = 1
screen_mode = "screen_saver"
screen_saver = "show_logo"
second_screen_fps = 1
second_screen_webui = false
bg_fg_select = "manu"
bg_mode = "normal"
fg_mode = "normal"
fg_image = ''
bg_color = 'black'
bg_image = "bg_480x320_static.png"
bg_anim_image = ''
font_sizes = [10, 8, 10, 25, 25, 9]
font = 'DejaVuSansMono'
font_bold = 'DejaVuSansMono-Bold'
status_font = 'DejaVuSansMono'
font_awesome = ''
size_offset = 5
label_spacing = 9
cursor = '❤'
friend_bars = '▌'
friend_no_bars = '│'
main_text_color = ['black']
color_mode = ['P', 'P']

[theme.menu.options]
motion_text = true
motion_text_speed = 20
bg_select = "manu"
bg_mode = "normal"
position = [ 0, 0,]
title_position = [ "center", "5",]
title_font_size = "Medium"
title_color = "black"
width = 100
height = "100%"
buttons_position = [ "center", "5",]
buttons_width = "90%"
button_height = 15
button_spacing = 3
bg_color = "white"
border_color = "black"
highlight_color = "black"
highlight_border_color = "white"
highlight_text_color = "white"
button_bg_color = "white"
button_bg_border_color = "black"
button_text_color = "black"
bg_image = ""
button_bg_image = ""
highlight_button_bg_image = ""
text_position = [ "center", "center",]
button_font_size = "Medium"
timeout = 30

[theme.widget.face]
position = [32, 100]
text_font_size = "Huge"
color = []
icon = true
icon_color = false
mask = false
refine = 150
image_type = 'png'
f_awesome = false
f_awesome_size = 40
zoom = 2
z_axis = 102

[theme.widget.name]
text_font = "sw.ttf"
position = [ 32, 195,]
text_font_size = "Bold"
color = [ "black",]
icon = false
f_awesome = false
f_awesome_size = 40
z_axis = 101
